services:
  web:
    build: .
    container_name: exercise_web
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5000 'app:app'"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      es:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: exercise_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-exercise_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: exercise_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  es:
    image: elasticsearch:8.9.0
    container_name: exercise_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  es_data: 