services:
  crawler:
    build: .
    container_name: exercise_crawler
    volumes:
      - ./dist:/app/dist
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app

volumes:
  postgres_data:
  redis_data:
  es_data: 